sudo: required
services:
  - docker
before_install:
  - docker build -t karthik540/dev-flask .
script:
  - echo "Success !"
after_success:
  - docker build -t karthik540/simple-flask .

  # Login to Docker hub..
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # Pushing the images...
  - docker push karthik540/simple-flask